project:
  type: book
  output-dir: docs

book:
  title: "管理会計"
  author: 
  - name: "佐久間 智広" 
    affiliation: "神戸大学大学院経営学研究科"
    email: "sakuma@port.kobe-u.ac.jp"
  date: today
  date-format: YYYY/MM/DD
  cover-image: logo_long.png
  chapters:
    - index.qmd
    - 1_intro_text.qmd
    - 2_管理会計の意義_text.qmd
    - 3_管理会計の基礎概念_text.qmd
    - 4_意思決定_text.qmd
    - 5_業績管理_text.qmd
    - 6_原価管理_text.qmd
    - 7_長期経営計画_text.qmd
    - references.qmd


subtitle: "2023年度　管理会計"
format:
  html:
    theme:
      light: [flatly,fonts.scss]
      dark: [darkly,fonts.scss]
    toc: true     
    toc-title: Contents
    toc-depth: 2
    number-sections: true
    number-depth: 3
    title-block-banner: false
    logo: kobe.png
    embed-resources: false
    code-fold: show
    pdf-separate-fragments: true
  pdf:
    documentclass: scrreprt
editor: visual
bibliography: references.bib
csl: the-accounting-review.csl
